
export const TimetableData = [
  {
    day: '月曜日',
    one: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0},
    two: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0, },
    three: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    four: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    five: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    six: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
  },
  {
    day: '火曜日',
    one: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    two: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    three: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    four: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    five: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    six: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
  },
  {
    day: '水曜日',
    one: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    two: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    three: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    four: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    five: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    six: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
  },
  {
    day: '木曜日',
    one: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    two: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    three: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    four: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    five: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    six: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
  },
  {
    day: '金曜日',
    one: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    two: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    three: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    four: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    five: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    six: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
  },
  {
    day: '土曜日',
    one: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    two: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    three: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    four: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    five: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
    six: { clannname: '', atted: '15', noatted: '5',nowattend:0,absent:0 },
  },
]